spring:
  application:
    name: crud-service
  profiles:
    active: mariadb
---

spring:
  profiles: mariadb
  datasource:
    url: jdbc:mariadb://localhost:3306/dating?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
    username: backend
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLInnoDBDialect
    database: mariadb
    openInView: false
    show_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      properties:
        hibernate.cache.use_query_cache: false
        hibernate.generate_statistics: true

---

spring:
  profiles: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    openInView: false
    show_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      properties:
        hibernate.cache.use_query_cache: false
        hibernate.generate_statistics: true