services:
  mariadb:
    image: mariadb:10.5.6
    volumes:
      - mariadb_data:/var/lib/mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employee_app
      MYSQL_USER: backend
      MYSQL_PASSWORD: password

volumes:
  mariadb_data:
    driver: local